### PR TITLE
add tonemapping framwork b/w rgb pipe and yuv pipe

### PR DESCRIPTION
**Pull request by yaowang1**
Details:
tonemapping pipe:
input: RGBA16
output: RGBA8
kernel do nothing, just copy highest 8bits of input to output

### CODE REVIEW

**Comment by windyuan** [comment]
others should be ok to me.
Thanks.

**Comment by yaowang1** [comment]
Reply "color_bits can read from 
input->get_video_info ();
you can refer from CLBayerPipeImageKernel::prepare_arguments"

Hi, feng
this color bits is not tonemapping cl's input color bits, it's the original color_bits: 10/12 as what I designed in yesterday's ppt. are there any other better design?

**Comment by windyuan** [comment]
Hi Yao,
   If so, you can left a member function , e.g  CLTonemappingImageKernel::set_initial_bits()... then cl_3a_image_processor or upper level can decide the bits.
Thanks
Wind

**Comment by yaowang1** [comment]
Hi, yuafeng
If so who will call set_initial_bits()? Only blc knows the initial bits
Thanks,
-Yao

**Comment by windyuan** [comment]
Hi Yao,
   It's a good question. 2 options for you.
1. you can leave the set_initial_bits in CLTonemappingImageHandler/CLTonemappingImageKernel. and hardcode the _initial_bits = 12; in the constructor. this can make your framwork/tests passed.
2. more decent way. 
    CLImageProcessor/ImageProcessor should keep input/ouput video info(not implemented yet). then
    CL3aImageProcessor can get both input/output videoinfo and set any related bits.
   I think you can follow step 1 firstly
Thanks,
Wind

**Comment by windyuan** [comment]
merged. thanks.

**Pull request closed without merging**
