### PR TITLE
xcamsrc: fix the webview failure

### PR DESCRIPTION
**Pull request by zjutoe**
mediapipe tried to reconfigure very early, even before the device
and subdevice started, which led to failure. So we start the device
and subdevice early.

### CODE REVIEW

**Comment by windyuan** [comment]
check comments

**Comment by zjutoe** [comment]
let me try that way

**Comment by zjutoe** [comment]
sounds good, let me try it.

**Comment by zjutoe** [comment]
I tried but failed.

Seems all the operations have to be done in bunch, and in _start().

Moving anything to _set_caps() would cause the device_manager->start () fail.
And I traced down to V4l2Device::request_buffer (). It's the io_control (VIDIOC_REQBUFS, &request_buf) will fail.

Really weird...

**Comment by windyuan** [comment]
merged as workaround.

**Pull request closed without merging**
