### PR TITLE
Move calibration parser to xcore.

### PR DESCRIPTION
**Pull request by wujunkai166**

### CODE REVIEW

**Comment by windyuan** [comment]
@wujunkai166 check CI build log
09:22:45,871 INFO  - /opt/media/build/libxcam/tests/test-image-stitching.cpp:94: undefined reference to `XCam::CalibrationParser::CalibrationParser()'
09:22:45,871 INFO  - /opt/media/build/libxcam/tests/test-image-stitching.cpp:142: undefined reference to `XCam::CalibrationParser::parse_intrinsic_param(char*, XCam::IntrinsicParameter&)'
09:22:45,871 INFO  - /opt/media/build/libxcam/tests/test-image-stitching.cpp:143: undefined reference to `XCam::CalibrationParser::parse_extrinsic_param(char*, XCam::ExtrinsicParameter&)'

**Comment by wujunkai166** [comment]
@windyuan

**Comment by windyuan** [comment]
looks good to me. will merge after CI build

**Comment by windyuan** [comment]
@uartie, looks like CI build stopped. any thing happened?

**Comment by uartie** [comment]
@windyuan The CI infrastructure has been powered down over the weekend while a new power transformer is being installed at the site.  My apologies, I thought you were on the distribution list for the email I sent out.  CI will be back online later today.

**Comment by uartie** [comment]
@windyuan you should have received the email notification about the CI powerdown... looks like you actually were on the distribution list.

**Comment by windyuan** [comment]
@uartie,  Sorry, I missed your mail of CI powerdown. looks it's back again. Thanks for your support.

**Pull request merged**
