### PR TITLE
    test-device-manager:  support configuration options for hdr,dns,snr

### PR DESCRIPTION
**Pull request by liuyinhx**
Usage:
       ./test-device-manager ... --hdr=rgb --dns=true --snr=true
    or ./test-device-manager ... --hdr rgb --dns true --snr true

### CODE REVIEW

**Comment by windyuan** [comment]
It is good to see you changed to long-options :).
please check comments.
and since you add lots options, please also add <--tnr mode> choice. you can try processor->set_tnr there. the mode support 'RGB', 'YUV' and 'both'

**Comment by liuyinhx** [comment]
ok, i‘ll change next version

**Comment by liuyinhx** [comment]
commit information deleted, i will re-pull later

**Comment by windyuan** [comment]
Merged with fix.
1. _enable_tnr changed to _tnr_mode. Please always remember to init *basic data type* in constructor
2. output format settings more generic

**Comment by windyuan** [comment]
skip last message

**Pull request closed without merging**
