### PR TITLE
add hdr on lab.

### PR DESCRIPTION
**Pull request by wang-fei**
test lab hdr cmd:
$./test-cl-image -t hdr -d lab -f rgba -i capture.rgba -o hdr_lab.rgba.

### CODE REVIEW

**Comment by windyuan** [comment]
1. patch of 'fix create cl memory from va image failed when use V4L2_PIX_FMT_RGB32' is not necessary, will remove.
2. patch of add hdr on lab', please refer to comments above, others looks good.
after fix, please re-submit.
Thanks.

**Comment by windyuan** [comment]
I'm trying to fix this patch but found kernel_hdr_rgb.cl missed. please add it and resubmit.

**Comment by wang-fei** [comment]
resubmit patch.
kernel_hdr_rgb.cl exists in my local commit, but missed on github. After resubmitting, this problem gone.

**Comment by windyuan** [comment]
merged and replace CLHdrImageKernel to CLImageKernel.
please pull latest code.

**Pull request closed without merging**
